### ISSUE TITLE
Client information

### ISSUE THREAD

**Issue by richoster** [spacebetweentherapy/website#93]
Create a 'client information' page in the same format as the contact page with the following fields:
First name*
Last name*
Preferred name
Gender
Pro nouns 
Date of Birth*
Contact number*
Email*
Home address*
Emergency Contact name*
Emergency Contact number*
I confirm I'm over 18* (tick box if possible)
GP/Practice name & number*
Relevant medical conditions or treatment
Any current prescribed medication
Any other supporting organisations

*required fields 

I'll knock up a few sentences to go at the top, something like "Please fill out the following form so I have basic information to provide the support - many thanks"

**Comment by crawlem** [comment]
I created the JotForm (link below) - and then wondered if that might be the best way of managing this form, rather than creating a page on the website? The advantage of leaving it in JotForm is you can control the fields without any changes to the website code. E.g. if you wanted to add a question, change a field to required etc.

https://form.jotform.com/220652108856052

**Comment by richoster** [comment]
Yep, that would work. It's what I thought originally, which then lead me to think about a form on the web page, just because I was thinking about it being pretty. But, it doesn't need to be super pretty and there is a good chance I will want to tweak the form from time to time. I also want to create a feedback form which I was going to do on Jotform. Shall I just create a separate account with my spacebetween address, I know you can only have 5 forms with the free version. What email have you used to create an account for the web enquiry form?

**Comment by crawlem** [comment]
Done
